apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: default
spec:
  encryptedData:
    image-creds.yaml: AgCumYW4f40/ve0nxxtBGu0u0Bk62X23s9jw7tU1yNNA96mKXxM52P9/xGuHpASet9Z7THtBuW8HEXKRZURSaT97+xHLqYpWIKS+xfhZlmrhytj/bkeHbZYehRhs94CfboKpsPIG4PuNEkQvaGbmNFdGsN9fPT91BGx49mC97yx2m3HU8p+GOvoipgNfgb8cGcklYSz0WLbePdun4hcYSFiIQessVezUJ6mmYE2UTS/7chWGtX6scB+EUxyx4/OhgFjCC1liBIOm3bmrTiVqfEo1lxsvKfzWKo1ZWzANCKBC+OosgtuBG6e8nSIcp+uNPoqPQO1b+Awc92Ht76rmzdjWdmZNaORQoE8bzvTQwHkBem6/IVxyoM10C7h7fnAmYKzRDqRAmFlarWLi/az6B6oCFoIPJEzgS3Z8rpsn7iQwRno21DupbNbpBPjQjfhrWraFB+8THztnANkdm7CqgwH3oPRo7ucUPFcs/lcWAz+Qn6qt1iZ75oj9HQ2XD5U8eTslqsY0dKNPrjeiPaRMadbA+D9tjIviAdAYHIW88coaWedVxgWXiGywiw4dpe5/aLOiicyedldX+zNs3RDtjtVbNlJB3x/WGJtF/jC0rtHAOMjqMVqGoPvoqwefcesLqU4EjucgOUzEBiVoV07Fs0Sd4tW288hgyDlKLab5NsVDKNr+H29Pb725KR1XmK60Z5hWU40PljZPeBEO4jTOKE2oIIvweyHAkpNma/SJk+ajOyubwBz3uXV1MQ==

